export const DEFAULT_CATS = [
  'Math', 'CS/CP', 'AI', 'Physics', 'Astronomy', 'Writing',
  'Science Communication', 'Science Research', 'Research Program',
  'Science Program', 'Economics', 'Engineering', 'Peace/Security',
  'Math/Science', 'Other',
];

export const DEFAULT_DATA = [
  { name: 'IOQM → IMO Track',            pipeline: 'IOQM → RMO → INMO → IMO',    type: 'Competition', category: 'Math',                   deadline: '2026-09-01', deadlineLabel: 'IOQM: Sep',                           notes: 'Primary math olympiad track. IOQM in Sep, RMO in Nov, INMO in Jan, IMO prep after.',                               eligibility: 'Grade 8–12, India',         status: 'Contemplating', priority: 'High'   },
  { name: 'ZCO/ZIO → IOI Track',          pipeline: 'ZCO/ZIO → INOI → IOI',        type: 'Competition', category: 'CS/CP',                  deadline: '2026-11-01', deadlineLabel: 'ZCO/ZIO: Nov',                        notes: 'Primary CS olympiad track. ZCO (algorithms) or ZIO (informatics) in Nov, INOI in Feb.',                           eligibility: 'Grade 8–12, India',         status: 'Contemplating', priority: 'High'   },
  { name: 'INAIO → IOAI',                 pipeline: 'INAIO → IOAI',                 type: 'Competition', category: 'AI',                     deadline: null,         deadlineLabel: 'Annual, check ACM India',              notes: 'Side AI track. Check ACM India website for schedule.',                                                            eligibility: 'School students, India',    status: 'Contemplating', priority: 'Medium' },
  { name: 'NSEP → IPhO Track',            pipeline: 'NSEP → INPhO → IPhO',          type: 'Competition', category: 'Physics',                deadline: '2026-11-01', deadlineLabel: 'NSEP: Nov',                           notes: 'Doable alongside JEE prep. NSEP in Nov, INPhO in Jan, IPhO in summer.',                                           eligibility: 'Grade 10–12, India',        status: 'Contemplating', priority: 'Medium' },
  { name: 'NSEA → IOAA Track',            pipeline: 'NSEA → INAO → IOAA',           type: 'Competition', category: 'Astronomy',              deadline: '2026-11-01', deadlineLabel: 'NSEA: Nov',                           notes: 'Fits aerospace interest. NSEA in Nov, INAO follows, IOAA in summer.',                                             eligibility: 'Grade 10–12, India',        status: 'Contemplating', priority: 'Medium' },
  { name: 'John Locke Essay Competition', pipeline: '',                              type: 'Competition', category: 'Writing',                deadline: '2026-03-31', deadlineLabel: 'Registration: Mar 31, Essay: May 31', notes: 'Philosophy, IR, History, Economics. Under 19, global prestige. Essay due May 31.',                                 eligibility: 'Under 19, global',          status: 'Contemplating', priority: 'High'   },
  { name: 'Breakthrough Junior Challenge',pipeline: '',                              type: 'Competition', category: 'Science Communication',  deadline: '2026-09-15', deadlineLabel: 'Sep 15',                              notes: '3-minute science video. Ages 13–18. $250K prize.',                                                                eligibility: 'Ages 13–18, global',        status: 'Contemplating', priority: 'High'   },
  { name: 'Regeneron ISEF',               pipeline: 'INSEF → ISEF',                 type: 'Competition', category: 'Science Research',       deadline: null,         deadlineLabel: 'Qualify via INSEF first',              notes: '1-year pipeline. Original research project, qualify via India\'s national science fair.',                          eligibility: 'Grade 9–12, global',        status: 'Contemplating', priority: 'High'   },
  { name: 'Plaksha Young Tech Scholars',  pipeline: '',                              type: 'Program',     category: 'Research Program',       deadline: null,         deadlineLabel: '~Mar–Apr',                            notes: 'India-based, interdisciplinary research program. Check Plaksha University website.',                              eligibility: 'School students, India',    status: 'Contemplating', priority: 'Medium' },
  { name: 'IISER Summer Outreach',        pipeline: '',                              type: 'Program',     category: 'Science Program',        deadline: null,         deadlineLabel: '~Apr',                                notes: 'Multiple IISERs run outreach programs. Hands-on science. Check each IISER website.',                              eligibility: 'School students, India',    status: 'Contemplating', priority: 'Medium' },
  { name: 'CMI STEMS',                    pipeline: '',                              type: 'Program',     category: 'Math/Science',           deadline: '2026-12-01', deadlineLabel: '~Dec',                                notes: 'Chennai Mathematical Institute. Online exam leads to residential camp.',                                           eligibility: 'Grade 9–12, India',         status: 'Contemplating', priority: 'Medium' },
  { name: 'Harvard Political Review Essay',pipeline: '',                             type: 'Competition', category: 'Writing',                deadline: null,         deadlineLabel: 'Check annually',                      notes: 'Geopolitics/IR focus. International HS students. Check HPR website each year.',                                   eligibility: 'HS students, global',       status: 'Contemplating', priority: 'Medium' },
  { name: 'F1 in Schools',                pipeline: '',                              type: 'Competition', category: 'Engineering',            deadline: '2026-09-01', deadlineLabel: 'World Finals: Sep',                   notes: 'Teams of 3–6, ages 9–19. Design and race miniature F1 cars. Qualify via national/regional rounds.',               eligibility: 'Ages 9–19, global (teams)', status: 'Contemplating', priority: 'Low'    },
  { name: 'Foyle Young Poets Award',      pipeline: '',                              type: 'Competition', category: 'Writing',                deadline: '2026-07-31', deadlineLabel: 'Jul 31',                              notes: 'UK Poetry Society. Ages 11–17. Submit up to 3 poems. Global competition.',                                        eligibility: 'Ages 11–17, global',        status: 'Contemplating', priority: 'Medium' },
  { name: 'Royal Economic Society',       pipeline: '',                              type: 'Competition', category: 'Economics',              deadline: null,         deadlineLabel: '~Jun',                                notes: 'Economics essay competition for global HS students. Check RES website.',                                          eligibility: 'HS students, global',       status: 'Contemplating', priority: 'Medium' },
  { name: 'Geneva Centre GCSP Prize',     pipeline: '',                              type: 'Competition', category: 'Peace/Security',         deadline: '2026-03-20', deadlineLabel: '~Mar 20',                             notes: 'Peace and security essay. Geopolitics/defense focus. Check GCSP website.',                                        eligibility: 'HS/University, global',     status: 'Contemplating', priority: 'Medium' },
];
